### ISSUE TITLE
[Windows] PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by HannanAkbar** [regebro/hovercraft#134]
```
Traceback (most recent call last):
  File "C:\Users\Hannan\AppData\Local\Programs\Python\Python36-32\Scripts\hovercraft-script.py", line 11, in <module>
    load_entry_point('hovercraft==2.3', 'console_scripts', 'hovercraft')()
  File "c:\users\hannan\appdata\local\programs\python\python36-32\lib\site-packages\hovercraft\__init__.py", line 147, in main
    generate(args)
  File "c:\users\hannan\appdata\local\programs\python\python36-32\lib\site-packages\hovercraft\generate.py", line 137, in generate
    args.skip_notes, args.mathjax)
  File "c:\users\hannan\appdata\local\programs\python\python36-32\lib\site-packages\hovercraft\generate.py", line 22, in rst2html
    with open(filepath, 'rb') as infile:
PermissionError: [Errno 13] Permission denied: 'source'
```

The `source` directory has the write permission.

**Comment by hyst329** [comment]
@HannanAkbar What is the `source` directory, what does it contain and needed for?

**Comment by regebro** [comment]
When installing Python for Windows, on the "Finished" screen it has a button for you to disable the path length limitation.

It is *possible* that not doing so would give this error, I haven't tried.

Without further response, I will close this issue soon, I've tried Hovercraft on Windows and found no obvious errors.

**Comment by regebro** [comment]
Closing.

**Comment by blogcraft** [comment]
@regebro I did what you said in the Python installer disabling the path length, and have the same error.

**Comment by regebro** [comment]
What command line do you use?

**Comment by HamrozPamir** [comment]
Exception:
Traceback (most recent call last):
  File "C:\Users\Jumaev\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\Jumaev\Anaconda3\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Users\Jumaev\Anaconda3\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Users\Jumaev\Anaconda3\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "C:\Users\Jumaev\Anaconda3\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "C:\Users\Jumaev\Anaconda3\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "C:\Users\Jumaev\Anaconda3\lib\site-packages\pip\wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "C:\Users\Jumaev\Anaconda3\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Jumaev\\Anaconda3\\Lib\\site-packages\\win32\\win32api.pyd

**Comment by HamrozPamir** [comment]
Could anyone help me to fix this error.... I would be very greatful

**Comment by regebro** [comment]
This is a Conda/Anaconda problem, it has nothing to do with Hovercraft.

**Comment by HamrozPamir** [comment]
Any suggestions would be appriciated

**Comment by regebro** [comment]
https://conda.io/docs/help-support.html is the only Suggestion I have.
