### ISSUE TITLE
Installation did not work

### ISSUE THREAD

**Issue by rwcitek** [regebro/hovercraft#137]
I started a new Docker instance of Ubuntu 16.04 ...
```
docker run -it --name hovercraft ubuntu:16.04 /bin/bash
```
I ran these commands ...
```
apt-get update
apt-get install python3 python3-pip
pip3 install -U pip setuptools
```
Unfortunately, installing hovercraft returned an error ...
```
# pip3 install hovercraft

Collecting hovercraft
  Downloading hovercraft-2.4.tar.gz (498kB)
    100% |################################| 501kB 1.5MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-chyn4spc/hovercraft/setup.py", line 8, in <module>
        description = readme.read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1731: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-chyn4spc/hovercraft/
```
Will be trying other Linux Docker containers.

**Comment by rwcitek** [comment]
Similar issue in a new Docker instance of Ubuntu 14.04 ...
```
docker run -it --name hovercraft ubuntu:14.04 /bin/bash
```
I ran these commands ...
```
apt-get update
apt-get install python3 python3-pip
pip3 install -U pip setuptools
```
Unfortunately, installing hovercraft returned a similar error ...
```
# pip3 install hovercraft
Downloading/unpacking hovercraft
  Downloading hovercraft-2.4.tar.gz (498kB): 498kB downloaded
  Running setup.py (path:/tmp/pip_build_root/hovercraft/setup.py) egg_info for package hovercraft
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/hovercraft/setup.py", line 8, in <module>
        description = readme.read()
      File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1731: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/hovercraft/setup.py", line 8, in <module>

    description = readme.read()

  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1731: ordinal not in range(128)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/hovercraft
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by kucharskim** [comment]
Not sure is this the way to go, but I had same issue.

```
--- setup.py.orig
+++ setup.py
@@ -4,10 +4,10 @@ import sys
 
 version = '2.4'
 
-with open('README.rst', 'rt') as readme:
+with open('README.rst', 'rt', encoding='utf-8') as readme:
     description = readme.read()
 
-with open('CHANGES.txt', 'rt') as changes:
+with open('CHANGES.txt', 'rt', encoding='utf-8') as changes:
     history = changes.read()
 
 class CustomInstall(install):

```

**Comment by regebro** [comment]
I can't duplicate this, but I have a hunch of what it is, so this should fix it.
