### ISSUE TITLE
External CSS file leads to "TypeError: Argument must be bytes or unicode, got 'NoneType'"

### ISSUE THREAD

**Issue by sumpfralle** [regebro/hovercraft#166]
I would like to use an external CSS file with hovercraft (and I think, this worked before):
```
:css: http://example.org/style.css
```

Sadly this triggers an exception (against a file containing only the single line above):
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lars/.virtualenvs/hovercraft/lib/python3.6/site-packages/hovercraft/__init__.py", line 45, in generate_and_observe
    monitor_list = generate(args)
  File "/home/lars/.virtualenvs/hovercraft/lib/python3.6/site-packages/hovercraft/generate.py", line 166, in generate
    args.slide_numbers)
  File "/home/lars/.virtualenvs/hovercraft/lib/python3.6/site-packages/hovercraft/generate.py", line 34, in rst2html
    tree = sm.walk()
  File "/home/lars/.virtualenvs/hovercraft/lib/python3.6/site-packages/hovercraft/parse.py", line 128, in walk
    method(node)
  File "/home/lars/.virtualenvs/hovercraft/lib/python3.6/site-packages/hovercraft/parse.py", line 198, in start_paragraph
    self.curnode.set(fieldname, value)
  File "src/lxml/etree.pyx", line 813, in lxml.etree._Element.set
  File "src/lxml/apihelpers.pxi", line 570, in lxml.etree._setAttributeValue
  File "src/lxml/apihelpers.pxi", line 1437, in lxml.etree._utf8
TypeError: Argument must be bytes or unicode, got 'NoneType'
```

This error is not triggered, when I remove the colon from the field content. But of course, I need a colon for a URL :(

Maybe external CSS files are not supported?
(my memory may fool me with this ...)

The following dependencies are installed:
```
argh==0.26.2
docutils==0.14
hovercraft==2.5
lxml==4.2.1
pathtools==0.1.2
pkg-resources==0.0.0
Pygments==2.2.0
PyYAML==3.12
svg.path==2.2
watchdog==0.8.3
```

**Comment by regebro** [comment]
That never worked. 

The error comes from you having a colon in the value, indeed, and you can get rid of it by escaping it with a backslash:

`:css: http:\//foo.com/path/whatever`

However, you will later get an error when it attempts to copy that file to the destination. I don't have any plans to support external css files, what is the reason you want it to be external?

**Comment by sumpfralle** [comment]
Thank you for the explanation of the current state!

> I don't have any plans to support external css files, what is the reason you want it to be external?

I wrote a hovercraft plugin for moinmoin: https://moinmo.in/ActionMarket/HoverCraft

It works as follows:
* user edits a wiki page (with the `rst` parser selected)
* user clicks on the action `view hovercraft` and enjoys the rendered html output
* the local hackspace uses this setup in its wiki containing workshops and presentations (e.g.: https://wiki.hack-hro.de/Workshops/Shell)
* the perfect CSS file location would obviously be a wiki attachment file (i.e. can be edited by all users of this wiki)
    * the cleanest way of specifying the location of that CSS file is by its wki-based URL

Thank you for your time!
