### ISSUE TITLE
Hovercraft dependency error

### ISSUE THREAD

**Issue by Endle** [regebro/hovercraft#56]
See <https://bitbucket.org/pypa/pypi/issue/215/hovercraft-dependency-error>

After `# pip install hovercraft`
```
$ hovercraft show
Traceback (most recent call last):
  File "/usr/bin/hovercraft", line 9, in <module>
    load_entry_point('hovercraft==1.1', 'console_scripts', 'hovercraft')()
  File "/usr/lib/python2.7/site-packages/hovercraft/__init__.py", line 18, in main
    from hovercraft.generate import rst2html, copy_resource
  File "/usr/lib/python2.7/site-packages/hovercraft/generate.py", line 8, in <module>
    from .template import CSS_RESOURCE
  File "/usr/lib/python2.7/site-packages/hovercraft/template.py", line 2, in <module>
    import configparser
ImportError: No module named configparser
```
`# pip install configparser ` fixed that

**Comment by regebro** [comment]
Hovercraft only supports Python 3, which includes the configparser module.
