### ISSUE TITLE
Getting syntax error

### ISSUE THREAD

**Issue by zeigerpuppy** [regebro/hovercraft#59]
I installed hovercraft in Debian Wheezy, using the procedure below, but whenever I try to compile the example hovercraft presentation, I get a syntax error.
I'm a bit stuck on how to fix this.

Error:
```
/hovercraft/docs/examples$ hovercraft hovercraft.rst output
Traceback (most recent call last):
  File "/opt/hover/.virtualenvs/env/bin/hovercraft", line 9, in <module>
    load_entry_point('hovercraft==2.0b1', 'console_scripts', 'hovercraft')()
  File "/opt/hover/.virtualenvs/env/lib/python3.2/site-packages/hovercraft/__init__.py", line 125, in main
    generate(args)
  File "/opt/hover/.virtualenvs/env/lib/python3.2/site-packages/hovercraft/generate.py", line 110, in generate
    args.skip_notes)
  File "/opt/hover/.virtualenvs/env/lib/python3.2/site-packages/hovercraft/generate.py", line 28, in rst2html
    xml = rst2xml(rststring)
  File "/opt/hover/.virtualenvs/env/lib/python3.2/site-packages/hovercraft/parse.py", line 76, in rst2xml
    settings_overrides={'syntax_highlight': 'short'})
  File "/opt/hover/.virtualenvs/env/lib/python3.2/site-packages/docutils/core.py", line 414, in publish_string
    enable_exit_status=enable_exit_status)
  File "/opt/hover/.virtualenvs/env/lib/python3.2/site-packages/docutils/core.py", line 657, in publish_programmatically
    pub.set_components(reader_name, parser_name, writer_name)
  File "/opt/hover/.virtualenvs/env/lib/python3.2/site-packages/docutils/core.py", line 96, in set_components
    self.reader.set_parser(parser_name)
  File "/opt/hover/.virtualenvs/env/lib/python3.2/site-packages/docutils/readers/__init__.py", line 63, in set_parser
    parser_class = parsers.get_parser_class(parser_name)
  File "/opt/hover/.virtualenvs/env/lib/python3.2/site-packages/docutils/parsers/__init__.py", line 50, in get_parser_class
    module = __import__(parser_name, globals(), locals(), level=1)
  File "/opt/hover/.virtualenvs/env/lib/python3.2/site-packages/docutils/parsers/rst/__init__.py", line 75, in <module>
    from docutils.parsers.rst import states
  File "/opt/hover/.virtualenvs/env/lib/python3.2/site-packages/docutils/parsers/rst/states.py", line 116, in <module>
    from docutils.parsers.rst import directives, languages, tableparser, roles
  File "/opt/hover/.virtualenvs/env/lib/python3.2/site-packages/docutils/parsers/rst/roles.py", line 78, in <module>
    from docutils.utils.code_analyzer import Lexer, LexerError
  File "/opt/hover/.virtualenvs/env/lib/python3.2/site-packages/docutils/utils/code_analyzer.py", line 12, in <module>
    import pygments
  File "/opt/hover/.virtualenvs/env/lib/python3.2/site-packages/pygments/__init__.py", line 37, in <module>
    from pygments.util import StringIO, BytesIO
  File "/opt/hover/.virtualenvs/env/lib/python3.2/site-packages/pygments/util.py", line 226
    return u'[%s-%s]' % (unichr(a), unichr(b))
                    ^
SyntaxError: invalid syntax
```

Install Procedure
```
sudo apt-get install python3 python3-pip python-dev python3-dev virtualenvwrapper python3-virtualenv # installs python 3.2
adduser hover
usermod --home /opt/hover -m hover #-m moves files too

su hover
cd ~
mkvirtualenv -p /usr/bin/python3.2 env

pip install hovercraft
```

**Comment by regebro** [comment]
Looks like the latest version of pygments requires Python 3.3. You can either upgrade to Python 3.3, or downgrade Pygments. I'm guessing 1.6 should work.

`pip uninstall pygments==1.6` seems to fix the problem.

**Comment by zeigerpuppy** [comment]
Thanks, yes downgrading pygments worked well

```
pip uninstall pygments
pip install pygments==1.6
```
