### ISSUE TITLE
Typo in template.py

### ISSUE THREAD

**Issue by valpo** [regebro/hovercraft#73]
Traceback (most recent call last):
  File "/usr/bin/hovercraft", line 9, in <module>
    load_entry_point('hovercraft==2.0b2.dev0', 'console_scripts', 'hovercraft')()
  File "/usr/lib/python3.3/site-packages/hovercraft-2.0b2.dev0-py3.3.egg/hovercraft/__init__.py", line 125, in main
    generate(args)
  File "/usr/lib/python3.3/site-packages/hovercraft-2.0b2.dev0-py3.3.egg/hovercraft/generate.py", line 110, in generate
    args.skip_notes)
  File "/usr/lib/python3.3/site-packages/hovercraft-2.0b2.dev0-py3.3.egg/hovercraft/generate.py", line 51, in rst2html
    tree.append(template_info.xml_node())
  File "/usr/lib/python3.3/site-packages/hovercraft-2.0b2.dev0-py3.3.egg/hovercraft/template.py", line 197, in xml_node
    if resource.extra_info == JS_POSIION_BODY:
NameError: global name 'JS_POSIION_BODY' is not defined

'JS_POSIION_BODY' is a typo, should be imho 'JS_POSITION_BODY'

**Comment by regebro** [comment]
OK, fixed by fahhem.
