### ISSUE TITLE
JSON_POSIION_BODY

### ISSUE THREAD

**Issue by mjibril** [regebro/hovercraft#77]
I get this issue when I try to run, "hovercraft hovercraft.rst",  in the examples directory

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/hovercraft-2.0b2.dev0-py3.4.egg/hovercraft/__init__.py", line 31, in generate_and_observe
    monitor_list = generate(args)
  File "/usr/local/lib/python3.4/dist-packages/hovercraft-2.0b2.dev0-py3.4.egg/hovercraft/generate.py", line 110, in generate
    args.skip_notes)
  File "/usr/local/lib/python3.4/dist-packages/hovercraft-2.0b2.dev0-py3.4.egg/hovercraft/generate.py", line 51, in rst2html
    tree.append(template_info.xml_node())
  File "/usr/local/lib/python3.4/dist-packages/hovercraft-2.0b2.dev0-py3.4.egg/hovercraft/template.py", line 197, in xml_node
    if resource.extra_info == JS_POSIION_BODY:
NameError: name 'JS_POSIION_BODY' is not defined

The solution that has worked for me is to checkout to commit 2ca3e8cfd00f5e28077d37bf142e1efd55a63df3  and reinstall hovercraft.

**Comment by regebro** [comment]
Duplicate (and now fixed).
