### ISSUE TITLE
reST include directive does not work

### ISSUE THREAD

**Issue by gregmuellegger** [regebro/hovercraft#79]
Hi I'm trying your awesome awesome tool to create a presentation. I wanted to include some code snippets and would preferably store them in separate files next to the `presentation.rst` file.

However I get the following output:

```
gregor@layka ~/projects/presentations/vagrant-primer (git)-[master] % hovercraft presentation.rst 
Serving HTTP on 0.0.0.0 port 8000 ...
<string>:183: (SEVERE/4) Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'vagrant_provision.sh'.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/docutils/io.py", line 236, in __init__
    self.source = open(source_path, mode, **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'vagrant_provision.sh'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/docutils/parsers/rst/directives/misc.py", line 75, in run
    error_handler=e_handler)
  File "/usr/lib/python3.4/site-packages/docutils/io.py", line 238, in __init__
    raise InputError(error.errno, error.strerror, source_path)
docutils.io.InputError: [Errno 2] No such file or directory: 'vagrant_provision.sh'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 2103, in run_directive
    result = directive_instance.run()
  File "/usr/lib/python3.4/site-packages/docutils/parsers/rst/directives/misc.py", line 83, in run
    (self.name, ErrorString(error)))
docutils.parsers.rst.DirectiveError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.4/site-packages/hovercraft/__init__.py", line 31, in generate_and_observe
    monitor_list = generate(args)
  File "/usr/lib/python3.4/site-packages/hovercraft/generate.py", line 110, in generate
    args.skip_notes)
  File "/usr/lib/python3.4/site-packages/hovercraft/generate.py", line 28, in rst2html
    xml = rst2xml(rststring)
  File "/usr/lib/python3.4/site-packages/hovercraft/parse.py", line 76, in rst2xml
    settings_overrides={'syntax_highlight': 'short'})
  File "/usr/lib/python3.4/site-packages/docutils/core.py", line 414, in publish_string
    enable_exit_status=enable_exit_status)
  File "/usr/lib/python3.4/site-packages/docutils/core.py", line 662, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/usr/lib/python3.4/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/usr/lib/python3.4/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/usr/lib/python3.4/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python3.4/site-packages/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/usr/lib/python3.4/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3.4/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 2961, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/usr/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.4/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3.4/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.4/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3.4/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 2299, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 2311, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 2054, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 2106, in run_directive
    line=lineno)
  File "/usr/lib/python3.4/site-packages/docutils/utils/__init__.py", line 193, in system_message
    raise SystemMessage(msg, level)
docutils.utils.SystemMessage: <string>:183: (SEVERE/4) Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'vagrant_provision.sh'.
```

The reST snippet in my presentation looks like this:

```rest
.. include:: vagrant_provision.sh
    :code: bash
```

The file is for sure available in the current directory and running `rst2html presentation.rst` does not throw any error but includes the file as expected.

I assume that it's an issue that the current working directory is misplaced somehow inside of Hovercraft!. When I give the absolute path to the `include` directive, everything works as expected.

**Comment by regebro** [comment]
What is your current directory when you try this? I was able to include a file that was in the current directory (which also happens to be where the presentation rst is located).

**Comment by gregmuellegger** [comment]
Hi, this is my test setup:

```
$ ls -a
.  ..  presentation.rst  test_include.sh

$ cat presentation.rst 
============
Include Test
============

---

``test_include.sh``
========================

.. include: test_include.sh
    :code: bash
(vagrant-primer) gregor@layka ~/projects/talks/vagrant-primer (git)-[master] % cat test_include.sh 
#!/bin/bash

echo "hi there"

$ hovercraft presentation.rst build 

$ cat build/index.html | sed "s/</\n</g"

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Include Test
</title>
<meta name="generator" content="Hovercraft! 1.0 http://regebro.github.com/hovercraft">
</meta>
<link rel="stylesheet" href="css/hovercraft.css" media="all">
</link>
<link rel="stylesheet" href="css/impressConsole.css" media="all">
</link>
<link rel="stylesheet" href="css/highlight.css" media="all">
</link>
</head>
<body class="impress-not-supported">
<div id="impress">
<div class="step step-level-1" step="0" data-rotate-x="0" data-rotate-y="0" data-rotate-z="0" data-scale="1" data-x="0" data-y="0" data-z="0">
<h1 id="test-include-sh">
<tt>test_include.sh
</tt>
</h1>
</div>
</div>
<div id="hovercraft-help">
<table>
<tr>
<th>Space
</th>
<td>Forward
</td>
</tr>
<tr>
<th>Right, Down, Page Down
</th>
<td>Next slide
</td>
</tr>
<tr>
<th>Left, Up, Page Up
</th>
<td>Previous slide
</td>
</tr>
<tr>
<th>P
</th>
<td>Open presenter console
</td>
</tr>
<tr>
<th>H
</th>
<td>Toggle this help
</td>
</tr>
</table>
</div>
<script type="text/javascript" src="js/impress.js">
</script>
<script type="text/javascript" src="js/impressConsole.js">
</script>
<script type="text/javascript" src="js/hovercraft.js">
</script>
</body>
</html>
```

With hovercraft 2.0 I don't get an error, but the file is not included in the exported HTML. You can reproduce it by cloning this gist: https://gist.github.com/gregmuellegger/489707a38a0f9e50d785
And then executing `hovercraft presentation.rst build`

**Comment by alem0lars** [comment]
I'm also having the same problem.

I have some "partials" inside the directory: `partials`, i.e. partials/slide1.rst points to the first slide of the presentation.

If I try to include `partials/slide1.rst` it doesn't work. If I use an absolute path it works.

Also, **the watchdog isn't working when I change partials**

**Comment by regebro** [comment]
You should have two colons after the include command. `.. include::`

**Comment by regebro** [comment]
The presentation not working when you change a file not being included is a different issue, and not entirely easy to fix, I'll created a new bug report for that. #91
