### ISSUE TITLE
Cant use hovercraft

### ISSUE THREAD

**Issue by harrizsb** [regebro/hovercraft#90]
Hi!
I got error when typing ```hovercraft test.rst Documents```

Here's the error
```
Traceback (most recent call last):
  File "/usr/local/bin/hovercraft", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/hovercraft/__init__.py", line 125, in main
    generate(args)
  File "/usr/local/lib/python3.4/dist-packages/hovercraft/generate.py", line 110, in generate
    args.skip_notes)
  File "/usr/local/lib/python3.4/dist-packages/hovercraft/generate.py", line 22, in rst2html
    with open(filepath, 'rb') as infile:
FileNotFoundError: [Errno 2] No such file or directory: 'test.rst'
```

**Comment by regebro** [comment]
Then test.rst doesn't exist.
