### ISSUE TITLE
Include directive - Relative paths not working

### ISSUE THREAD

**Issue by alem0lars** [regebro/hovercraft#96]
Hi,

I've created a "partial" rst file and I want to include it (using the `include` directive):

```
.. include::
   partials/jail.rst
```

I've placed the file in `partials/jail.rst` but I get the following exception:

```
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.3.6/lib/python3.3/threading.py", line 901, in _bootstrap_inner
    self.run()
  File "/usr/local/var/pyenv/versions/3.3.6/lib/python3.3/threading.py", line 858, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/alem0lars/Downloads/oym-2015/.venv/lib/python3.3/site-packages/hovercraft/__init__.py", line 31, in generate_and_observe
    monitor_list = generate(args)
  File "/Users/alem0lars/Downloads/oym-2015/.venv/lib/python3.3/site-packages/hovercraft/generate.py", line 110, in generate
    args.skip_notes)
  File "/Users/alem0lars/Downloads/oym-2015/.venv/lib/python3.3/site-packages/hovercraft/generate.py", line 28, in rst2html
    xml = rst2xml(rststring)
  File "/Users/alem0lars/Downloads/oym-2015/.venv/lib/python3.3/site-packages/hovercraft/parse.py", line 76, in rst2xml
    settings_overrides={'syntax_highlight': 'short'})
  File "/Users/alem0lars/Downloads/oym-2015/.venv/lib/python3.3/site-packages/docutils/core.py", line 414, in publish_string
    enable_exit_status=enable_exit_status)
  File "/Users/alem0lars/Downloads/oym-2015/.venv/lib/python3.3/site-packages/docutils/core.py", line 662, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/Users/alem0lars/Downloads/oym-2015/.venv/lib/python3.3/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/Users/alem0lars/Downloads/oym-2015/.venv/lib/python3.3/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/Users/alem0lars/Downloads/oym-2015/.venv/lib/python3.3/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/Users/alem0lars/Downloads/oym-2015/.venv/lib/python3.3/site-packages/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/Users/alem0lars/Downloads/oym-2015/.venv/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/Users/alem0lars/Downloads/oym-2015/.venv/lib/python3.3/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/alem0lars/Downloads/oym-2015/.venv/lib/python3.3/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/alem0lars/Downloads/oym-2015/.venv/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 2301, in explicit_markup
    self.explicit_list(blank_finish)
  File "/Users/alem0lars/Downloads/oym-2015/.venv/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 2331, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "/Users/alem0lars/Downloads/oym-2015/.venv/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 319, in nested_list_parse
    node=node, match_titles=match_titles)
  File "/Users/alem0lars/Downloads/oym-2015/.venv/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/alem0lars/Downloads/oym-2015/.venv/lib/python3.3/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/alem0lars/Downloads/oym-2015/.venv/lib/python3.3/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/alem0lars/Downloads/oym-2015/.venv/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 2604, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Users/alem0lars/Downloads/oym-2015/.venv/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 2311, in explicit_construct
    return method(self, expmatch)
  File "/Users/alem0lars/Downloads/oym-2015/.venv/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 2054, in directive
    directive_class, match, type_name, option_presets)
  File "/Users/alem0lars/Downloads/oym-2015/.venv/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 2106, in run_directive
    line=lineno)
  File "/Users/alem0lars/Downloads/oym-2015/.venv/lib/python3.3/site-packages/docutils/utils/__init__.py", line 193, in system_message
    raise SystemMessage(msg, level)
docutils.utils.SystemMessage: <string>:10: (SEVERE/4) Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'partials/jail.rst'.
```

I've further investigated and the problem is relative paths aren't resolved correctly since the current working directory is an empty temporary directory (in that case `/private/var/folders/9l/6h8r1n5n2cd92xrvn4jk2dyw0000gn/T/tmp1_6uen`) and the path is `partials/jail.rst` so it doesn't exit.

**Comment by alem0lars** [comment]
Pull-request #97 fixes this issue.
